dist: trusty
sudo: required
language: go
install:
- go get github.com/ValeLint/vale
- rm -rf public || exit 0
script:
- vale content
- bin/hugo
after_success:
- bash deploy.sh
env:
  global:
  - GIT_DEPLOY_DIR=public
  - GIT_DEPLOY_BRANCH=gh-pages
  - GIT_DEPLOY_USERNAME="Travis CI"
  - GIT_DEPLOY_EMAIL=joseph@jdkato.io
  - secure: DJru+SEhMXtPDPdhULMGy6ysTMglLy4YA+ApBPb6ywVwpX7lfOKs0tvbpsxWoy4vywkz8yVUIHNXQ22n0X8bYB2eD68mP17BblWCFowW2PivnSIeqdZyiOg1IDLJuDuNzww+RXXwqvtQf0hYf8xjTLhbE9HLgAjAAI2/ZFj/jvetrBOpDspfVIAYzvfL+cy1sIhC2BEg+QBP8FhCnBBmDxsktSVlT1KcQHuzgmFO93CM8ifnzl9wAeH33u6pEsLXi6WiQ43isR9UKsUZ8Pe2tpBav4sqvpKaANR1R6z1OrSj6Xrg36JONlYOjFXfLKnVp3AGsmY19f9BeBGkSYFoyYS2VupEVGYHP5QKN0eoY/QdjP8YS+Tx1qTAOs4dpj4lKl1NKqIeIuimDkgQW3/Zq6vSDiP5bDm6DKA+XSryBitca5zoC0lksSeRaOoWiwaSaz6qTC5lI7zd7MDJVHedv7s5UC2IVeVclA6nFtT7KhzF0qLt3cVIw3qXGbuHVI6UsMJEFiXqwdZHmdTZboDeXsWcL7l+op83mRC/jvDOdZe5aMLrRWR4ubXlZOpsmSBdPrPlUe7t6cX1O5Hxg/rdSy6zFG6HkopOdt/x8DPb43ffwbsp4c+Ubb56DUBeIeXBii696IxEt2/RNPx2pOG4XLHblTRnCeGbFHQl6C/95cE=
  only:
  - master
