dist: trusty
sudo: required
language: python
install:
  - pip install -r requirements.txt
  - go get github.com/ValeLint/vale
script:
  - vale content
after_success:
  - mkdocs build --verbose --clean --strict
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: site
  on:
    branch: master
