dist: trusty
sudo: required
language: python
before_install:
  - export GOPATH=$HOME/golang
  - export PATH=$PATH:$GOPATH/bin
install:
 - pip install -r requirements.txt
 - eval "$(gimme 1.7)"
 - go get github.com/ValeLint/vale
script:
- vale content
after_success:
- mkdocs build --verbose --clean --strict
deploy:
 provider: pages
 skip_cleanup: true
 github_token: $GITHUB_TOKEN
 local_dir: site
 on:
   branch: master
